* run-xephyr
Xephyr is a nested X server that runs as an X application, as long as you give Xephyr a display number that programs can use to connect to run inside the Xephyr window. This allows the user to run an entire X desktop inside a single window from a remote host or a local container.
~run-xephyr~ makes this usage simple. It does the following:
1. Look for an available display.
2. Run Xephyr with that display number.
3. Start a terminal inside the running Xephyr with the new DISPLAY, enabling you to run any commands you want inside the window.
NOTE: This does work best on either a separate container or host, as dbus conflicts can occur running multiple desktops as the same user on the same system.
** Requirements
1. Common Lisp (tested with SBCL) with Quicklisp installed. The included build script requires [[https://github.com/roswell/roswell][roswell]] to be already installed.
2. Xephyr X-server
   On Ubuntu you can install it with
   #+BEGIN_SRC shell
   sudo apt install xserver-xephyr
   #+END_SRC
   On OpenIndiana you can install it with
   #+BEGIN_SRC shell
   sudo pkg install xephyr
   #+END_SRC
** Building
The included build script assumes you have [[https://github.com/roswell/roswell][roswell]] installed and running.
1. Clone this repo somewhere in your Quicklisp path (recommended ~/.roswell/local-projects~ for most)
   #+BEGIN_SRC shell
   cd ~/.roswell/local-projects && git clone https://github.com/timotheosh/run-xephyr.git
   #+END_SRC
2. Run the build script.
   #+BEGIN_SRC shell
   ./build.sh
   #+END_SRC
3. Copy the binary somewhere on your path.
   #+BEGIN_SRC shell
   cp target/run-xephyr ~/.local/bin/
   #+END_SRC
** Usage
Just run
#+BEGIN_SRC shell
run-xephyr
#+END_SRC
